### ISSUE TITLE
gra 3x3

### ISSUE THREAD

**Issue by juliazon** [juliazon/kolko_i_krzyzyk#1]

**Comment by marcjannabakowska** [comment]
Dodałam plik kółko_i_krzyżyk_ver1, gdzie jest zaimplementowana działająca gra dla planszy 3x3, po wybraniu planszy 3x3 pierwszy wybór pola należy do kółka kolejny do krzyżyka. Po wygraniu przez jedną stronę gry pojawia się komunikat o tym ( trzeba napisać kto wygrał ). Dodałam możliwość wyboru planszy 4x4 i 5x5, ale nie wykonują się dobrze ( algorytm wygrywania jest błędny), program łatwo się wysypuje, warto zabezpieczyć przed nieoczekiwanymi wartościami, nie ma komunikatu, że nikt nie wygrał.
